### ISSUE TITLE
Adding example outputs to repo!?

### ISSUE THREAD

**Issue by ludaesch** [dodaro/cnl2asp#2]
The directory https://github.com/dodaro/cnl2asp/tree/main/src/examples contains some nice examples - thank you!

Could you also add the output files for your examples to the repo? For example  `python3.10 src/main.py src/examples/3Col 3Col.lp` should create a file `3Col.lp` that would be interesting to see, even without installing your tool. 

Note that I wasn't able to install and run the tool (similar to Issue #1 ).

**Comment by dodaro** [comment]
Thank you for the suggestion!

I added generated asp encodings in the examples folder. I also fixed the import issue.
