### ISSUE TITLE
Possible Error in the Parser?

### ISSUE THREAD

**Issue by GregGelfond** [dodaro/cnl2asp#4]
`cnl2asp` fails to compile the following example:

```
Aircraft goes from 1 to 5.
Pilot is one of Raptor, Eagle, Bullet, Falcon, Cowboy.
Every aircraft must be assigned to exactly 1 pilot.
It is prohibited that there is an aircraft A where the number of pilots assigned to A is greater than 1.
```

the error appears to be:

```
Parser error at line 4, col 84. Unexpected char "i":
A where the number of pilots assigned A is greater than 1.
                                        ^
Expected one of:
 * WHERE
 * COMMA
 * OF
 * COMPARISON_OPERATOR
 * PARAMETER_PREPOSITION
 * THAT
```

I'm not quite sure what is going on here really since the example is almost a verbatim copy/paste from another working example with the exception of the nouns `pilots` and `aircraft`.

**Comment by dodaro** [comment]
Thank you for your feedback! You have to add "that are" after "number of pilots". The following sentence is expected to work:

"It is prohibited that there is an aircraft A where the number of pilots that are assigned to A is greater than 1."

P.S. you might be interested in using our new online tool: [link](https://cnl2asp.streamlit.app?cnl=eJxtkMtugzAQRX+JR6jKootCgzFKqAAFP3bYJjaJnSJRHODr62TVSt16ZnzOvf1aXJhZzjyslQDtN0WRx1f4Aq/ZyE25EkQ9CISl+CjprbCseV9gXlv4cZoxiKoOLVakycjXxDJzkiwg8mSyuwDxekiTjCAx0eYuq1s7MdB67g0QtFxYsJvgvrQiKGzfRJxd24DiIoLgN9f3eVhJ4v4luNw6JGaKKinAq6RYKRLWU//0SUYGYu+gl7nBleycK88L2wE9dLjWNE28DmSe8/5yDA2B3hxn/sPa76UIlOaOJYByO5HPUKH5kFg6JPdnzvz4mCmXV/F/nKrm2cONm/bR5frgEbSTx2Y3HNJiFSg68yCehHGzy2hcD5vrZmCh80P+2JvT8GmoYnmp3f5G0aJdRk2zeOuRP7Bg2dwdw9h7+wE1sJiv%21).

**Comment by GregGelfond** [comment]
Thanks - that fixed the issue. Sometimes it's hard to interpret the error messages, and something like this is somehow easy to miss.
